version: '3.4'
services:
  mongo:
    image: 'mongo:5.0.3'
    ports:
      - '27017:27017'
  api:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - '4002:4000'
    depends_on:
      - mongo
    volumes:
      - './node_modules:/app/node_modules'
    user: root
